FasterKP/Models/ContextDb.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace FasterKP.Models
{
	public class ContextDb : DbContext 
	{
		public DbSet<DeviceModel> DeviceModels { get; set; }
		public DbSet<UserModel> UserModels { get; set; }
		public ContextDb (): base("FasterKpDB")
			{
		}

	}
}

FasterKP/Models/DescriptionModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FasterKP.Models
{
	public class DescriptionModel
	{
		[Key]
		public int ID { get; set; }
		public string Title { get; set; }
		public string Description { get; set; }

	}
}

FasterKP/Models/DeviceModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FasterKP.Models
{
	public class DeviceModel
	{
		[Key]
		public int ID { get; set; }
		public string Name { get; set; }
		public int Price { get; set; }
		public List <DescriptionModel> Description { get; set; }

	}
}

FasterKP/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FasterKP.Models
{
	public class UserModel
	{
		public int ID { get; set; }
		public string Login { get; set; }
		public string Password { get; set; }
		public string Name { get; set; }
		public string Position { get; set; }
		public string Surname { get; set; }
		public string Telefon_number { get; set; }
		public  string Image_name { get; set; }
		public bool Is_admin { get; set; }
	}	
}

FasterKP/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FasterKP.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View("~/Views/Admin/AdminAutorization.cshtml");
        }
    }
}

FasterKP/Controllers/GeneralController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using FasterKP.Models;
using System.Net.Http;
using System.Web.Http;
using System.Data.Entity.Migrations;

namespace FasterKP.Controllers
{
    public class DevicesController : ApiController
    { 
		[HttpPost]
		public bool AddOrUpdateNewDevice([FromBody]DeviceModel deviceModel)
		{
			try
			{
				using (ContextDb contextDb = new ContextDb()) { contextDb.DeviceModels.AddOrUpdate(deviceModel); contextDb.SaveChanges(); }

				return true;
			}
			catch  {return false; }
		}
		[HttpGet]
		public bool DeleteDevice(int ID)
		{

			try
			{
				using (ContextDb contextDb = new ContextDb()) { contextDb.DeviceModels.Remove(contextDb.DeviceModels.Find(ID)); contextDb.SaveChanges(); }
				return true;
			}
			catch { return false; }
		}
		
    }
}

FasterKP/Controllers/ImageDownloadController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Http;

namespace FasterKP.Controllers
{
    public class ImageDownloadController : ApiController
    {
	    private bool CheckDirectory(string directory, string imagename = null)
	    {
		    if (Directory.Exists(directory))
		    {
			    if (!string.IsNullOrEmpty(imagename))
				   return File.Exists(directory + $"\\{imagename}.png");
			    return true;
		    }
		    return false;
	    }

	    [HttpGet]
	    public async Task<byte[]> GetImage([FromUri] string nameImage)
	    {
		    try
		    {
			    if (CheckDirectory(HostingEnvironment.ApplicationPhysicalPath + $"\\Userimages"))
				    if (CheckDirectory(HostingEnvironment.ApplicationPhysicalPath + $"\\Userimages", nameImage))
				    {
					    return File.ReadAllBytes(HostingEnvironment.ApplicationPhysicalPath + $"\\Userimages\\{nameImage}.png");
				    }

			    return null;
			}
		    catch (Exception e)
		    {
			    return null;
		    }

	    }

	    [HttpPost]
	    public async Task<bool> UploadImage([FromBody]string nameImage)
	    {
		    try
		    {
				if (!CheckDirectory(HostingEnvironment.ApplicationPhysicalPath + $"\\Userimages"))
				    Directory.CreateDirectory(HostingEnvironment.ApplicationPhysicalPath + $"\\Userimages");
			    if (!CheckDirectory(HostingEnvironment.ApplicationPhysicalPath + $"\\Userimages", nameImage))
			    {
				    File.WriteAllBytes(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + $"\\Userimages\\{nameImage}.png",
					    await Request.Content.ReadAsByteArrayAsync());
				    return true;
			    }

			    return false;

		    }
		    catch (Exception e)
		    {
			    return false;
		    }
	    }
	}
}

FasterKP/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using FasterKP.Models;
using Microsoft.Ajax.Utilities;

namespace FasterKP.Controllers
{
    public class UsersController : ApiController
    {
		[HttpPost]
		public bool AddOrUpdateNewUser([FromBody]UserModel userModel)
		{
			try
			{
				using (ContextDb contextDb = new ContextDb()) { contextDb.UserModels.AddOrUpdate(userModel); contextDb.SaveChanges(); }
				return true;
			}
			catch  { return false; }
		}
		[HttpGet]
		public bool DeleteUser(int ID)
		{
			try
			{
				using (ContextDb contextDb = new ContextDb()) { contextDb.UserModels.Remove(contextDb.UserModels.Find(ID)); contextDb.SaveChanges(); }
				return true;
			}
			catch { return false; }
		}
		[HttpGet]
		public UserModel Login(string login, string password)
		{
			try
			{
				using (ContextDb contextDb = new ContextDb())
				{
					var user = contextDb.UserModels.FirstOrDefault(f => f.Login == login && f.Password == password);
					return user;
				}
			}
			catch { return null; }
		}
	}
}

FasterKP/Views/Admin/AdminAutorization.cshtml
@*@{
    ViewBag.Title = "AdminAutorization";
}*@

@*<h2>AdminAutorization</h2>*@

<!DOCTYPE html>

<html>
<head>
    <title>Авторизция</title>
    <style type="text/css">
        .login {
            width: 200px;
            background: #333333;
            padding: 5px;
            border: solid 2px black;
            float: left;
            position: center;
            top: 10px;
        }

        .password {
            width: 200px;
            background: #999999;
            padding: 5px;
            border: solid 2px #333333;
            float: left;
            position: center;
            top: 30px;
        }
    </style>

</head>
<body>
    <div class="login">ЛОГИН</div>
    <div class="password">ПАРОЛЬ</div>
</body>
</html>

FasterKP/Views/Shared/View.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Авторизция</title>
    <style type="text/css">
        .login {
            width: 200px;
            background: #333333;
            padding: 5px;
            border: solid 2px black;
            float: left;
            position: center;
            top: 10px;
        }
        .password {
            width: 200px;
            background: #999999;
            padding: 5px;
            border: solid 2px #333333;
            float: left;
            position: center;
            top: 30px;
        }
    </style>

</head>
<body>
<div class="login">ЛОГИН</div>
<div class="password">ПАРОЛЬ</div>
</body>
</html>

FasterKP/Views/Shared/_Layout.cshtml
@using System.Web.Mvc.Html
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>