AdminWeb/Models/BaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class BaseModel
	{
		public int ID { get; set; }
		public string Name_KP { get; set; }
		public string Date_KP { get; set; }
		public string Name_SB { get; set; }
		public string Date_SB { get; set; }
		public string Login { get; set; }
		public string Name_Manager { get; set; }
		public string Surname_Manager { get; set; }
		public string Name_Company { get; set; }
		public string Name_Client { get; set; }
		public string Post_Client { get; set; }
	}
}

AdminWeb/Models/DeviceModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class DeviceModel
	{
		public int ID { get; set; }
	    public string Type { get; set; }
        public string Block { get; set; }
        public string Display { get; set; }
        public string Header { get; set; }
        public string Name { get; set; }
		public string Price { get; set; }
        public string Description { get; set; }
        
		//public List <DescriptionModel> Description { get; set; }

	}
}

AdminWeb/Models/Headers.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Windows.Media;
using Faster_Kp_Client.Annotations;

namespace AdminWeb.Models
{
	public class Headers : INotifyPropertyChanged
	{
		private string _head;
		public string Head
		{
			get => _head;
			set
			{
				_head = value;
				OnPropertyChanged();
			}
		}
		private ObservableCollection<Item> _collection;
		public ObservableCollection<Item> Collection
		{
			get => _collection ?? (_collection = new ObservableCollection<Item>());
			set
			{
				_collection = value;
				OnPropertyChanged();
			}
		}


		public event PropertyChangedEventHandler PropertyChanged;

		[NotifyPropertyChangedInvocator]
		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}

	public class CollectHeads
	{
		private ObservableCollection<Headers> _headerses;

		public ObservableCollection<Headers> Headerses
		{
			get => _headerses ?? (_headerses = new ObservableCollection<Headers>());
			set => _headerses = value;
		}
	}
	public class Item : INotifyPropertyChanged
	{
		private string _property;
		public string Property
		{
			get => _property;
			set
			{
				_property = value;
				OnPropertyChanged();
			}
		}
		private string _price;
		public string Price
		{
			get => _price;
			set
			{
				_price = value;
				OnPropertyChanged();
			}
		}
	    private string _desc;
	    public string Desc
	    {
	        get => _desc;
	        set
	        {
	            _desc = value;
	            OnPropertyChanged();
	        }
	    }

        public event PropertyChangedEventHandler PropertyChanged;

		[NotifyPropertyChangedInvocator]
		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	public class ImageModels : INotifyPropertyChanged
	{
		private string _path;
		public string Path
		{
			get => _path;
			set
			{
				_path = value;
				OnPropertyChanged();
			}
		}
		private string _name;
		public string Name
		{
			get => _name;
			set
			{
				_name = value;
				OnPropertyChanged();
			}
		}



		public event PropertyChangedEventHandler PropertyChanged;

		[NotifyPropertyChangedInvocator]
		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

AdminWeb/Models/ResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class ResultModel
	{
		private string _text { get; set; }
		public string Text
		{
			get => _text;
			set => _text = value;
		}
	}
}

AdminWeb/Models/TypesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
    public class TypesModel
    {
        public bool IS { get; set; }
        public bool IP { get; set; }
        public bool SK { get; set; }
        public bool ST { get; set; }
    }
}

AdminWeb/Models/UploadModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class UploadModel
	{
		public byte[] pathd { get; set; }
		public byte[] pathe { get; set; }
		public string login { get; set; }
		public string name { get; set; }
		public int ID { get; set; }
	}
}

AdminWeb/Models/UserContext.cs
using AdminWeb.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using Faster_Kp_Client.KPPages;

namespace AdminWeb.Models
{
	public class UserContext:DbContext
	{
		public UserContext() :
			base("FastersKpDB")
		{ }
		public DbSet<UserModel> UserModels { get; set; }
        public DbSet<BaseModel> BaseModels { get; set; }
        public DbSet<DeviceModel> DeviceModels { get; set; }
    }
}

AdminWeb/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class LoginModel
	{
		[Required]
		public string Login { get; set; }

		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }
	}
	public class RegisterModel
	{
		[Required]
		public string Name { get; set; }

		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }

		[Required]
		public int ID { get; set; }

		[Required]
		public string Login { get; set; }

		[Required]
		public string Position { get; set; }

		[Required]
		public string Surname { get; set; }

		[Required]
		public string Telefon_number { get; set; }

		[Required]
		public string Image_name { get; set; }
		[Required]
		public bool Is_admin { get; set; }
		[Required]
		public bool Is_active { get; set; }
	}
	public class UserModel
	{
		public int ID { get; set; }
		public string Login { get; set; }
		public string Password { get; set; }
		public string Name { get; set; }
		public string Position { get; set; }
		public string Surname { get; set; }
		public string Telefon_number { get; set; }
		public string Image_name { get; set; }
		public bool Is_admin { get; set; }
		public bool Is_active { get; set; }
	}	
}

AdminWeb/Models/UsersList.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public static class UsersList
	{
		private static ObservableCollection<UserModel> _users;

		public static ObservableCollection<UserModel> Users
		{
			get => _users ?? new ObservableCollection<UserModel>();
			set => _users = value;
		}
	}
}

AdminWeb/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Windows.Threading;
using AdminWeb.Models;

namespace AdminWeb.Controllers
{
    public class ImagesController : Controller
    {
        // GET: Images
        public ActionResult Models()
        {
            return View();
        }

        public ActionResult CheckFiles(string folder)
        {
           
            ObservableCollection<ImageModels> Modelses = new ObservableCollection<ImageModels>();
            System.Windows.Threading.Dispatcher Dispatcher = Dispatcher.CurrentDispatcher;
            var derDirectories = Directory.GetDirectories(HostingEnvironment.ApplicationPhysicalPath + $@"\Models");
            var files = Directory.GetFiles(derDirectories.FirstOrDefault(x => x.Contains(folder)));
            if (files.Length == 0)
            {
                return null;
            }
            foreach (var x in files.Where(t => t.Contains(".png") || t.Contains(".jpg")))
            {
                Dispatcher.Invoke(() =>
                {
                    FileInfo fileInfo = new FileInfo(x);
                    Modelses.Add(new ImageModels
                        { Name = fileInfo.Name.Replace(".png", "").Replace(".jpg", ""), Path = "http://195.133.1.197:2019/Api/table/getimage/?nameImage=" + fileInfo.Name + "&type=" + folder });

                });

            }

            return PartialView(Modelses);
        }

        public ActionResult DeleteFile(string folder, string name)
        {
            string[] derDirectories = Directory.GetDirectories(HostingEnvironment.ApplicationPhysicalPath + $@"\Models");
            System.IO.File.Delete(Directory.GetFiles(derDirectories.FirstOrDefault(x => x.Contains(folder))).FirstOrDefault(t => t.Contains(name)));
            Directory.GetFiles(derDirectories.FirstOrDefault(x => x.Contains(folder)))
                .FirstOrDefault(t => t.Contains(name));
            return CheckFiles(folder);
        }
    }
}

AdminWeb/Views/Images/CheckFiles.cshtml
@using AdminWeb.Models
@model System.Collections.ObjectModel.ObservableCollection<AdminWeb.Models.ImageModels>

@foreach (ImageModels models in Model)
{
    <div class="models" style="float: left; border: 2px #666666 solid; border-radius: 5px; margin: 5px">
        <img class="buttonclose" style="height: 20px; width: 20px; float: right; margin: 2px" src="~/Icons/x-button.png"/>
        <img style="height: 150px; width: 200px; float: left;" src="@models.Path"/>
        <br/>
        <text class="namemodel" style="margin: 2px">@models.Name</text>
    </div>
}

AdminWeb/Views/Images/Models.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Models</title>
</head>
<header>
    <h2>Выберите типы оборудования</h2>
</header>
<footer>
    @using (Ajax.BeginForm("CheckFiles", "Images", new AjaxOptions { UpdateTargetId = "check" }))
    {
        <div id="main">

            <input class="checkboxtype" type="radio" name="IS" value="ИНТЕРАКТИВНЫЕ СТОЛЫ" />
            <label>Столы</label>


            <input class="checkboxtype" type="radio" name="IP" value="ИНТЕРАКТИВНЫЕ ПАНЕЛИ" />
            <label>Панели</label>


            <input class="checkboxtype" type="radio" name="SK" value="СЕНСОРНЫЕ КИОСКИ" />
            <label>Киоски</label>

            <input class="checkboxtype" type="radio" name="ST" value="СЕНСОРНЫЕ ТЕРМИНАЛЫ" />
            <label>Терминалы</label>

            <input class="checkboxtype" type="radio" name="ss" value="ВИРТУАЛЬНЫЙ ПРОМОУТЕР" />
            <label>Столы</label>

            <input class="checkboxtype" type="radio" name="sq" value="ГОЛОГРАФИЧЕСКАЯ ПИРАМИДА" />
            <label>Панели</label>


            <input class="checkboxtype" type="radio" name="se" value="ГОЛОГРАФИЧЕСКИЙ ВЕНТИЛЯТОР" />
            <label>Киоски</label>

            <input class="checkboxtype" type="radio" name="st" value="ГОЛОГРАФИЧЕСКИЙ КУБ" />
            <label>Терминалы</label>

            <input type="hidden" name="folder" />
            <input type="submit" hidden />
        </div>

    }
    @using (Ajax.BeginForm("DeleteFile", "Images", new AjaxOptions { UpdateTargetId = "check" }))
    {
        <input type="hidden" id="fdd" name="folder" />
        <input type="hidden" id="nameimage" name="name" />
        <input type="submit" id="kkk" hidden />
    }
    <button style="background: #ff1111" id="refresh">ОБНОВИТЬ</button>

</footer>
<body>
<div id="check"></div>

@Scripts.Render("~/scripts/jquery-3.3.1.js")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
<script>
    $(function() {
        $(document).on('change',
            '.checkboxtype',
            function() {
                $(this).parent().children('input:hidden').val($(this).val());
                $('#fdd').val($(this).val());
                $(this).parent().children('input:submit').click();
            });
        $(document).on('click',
            '.buttonclose',
            function() {
                $('#nameimage').val($(this).parent().children('input:text').text());
                $('#kkk').click();
            });
    });
   
        </script>
</body>
</html>