AdminWeb/Models/BaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class BaseModel
	{
		public int ID { get; set; }
		public string Name_KP { get; set; }
		public string Date_KP { get; set; }
		public string Name_SB { get; set; }
		public string Date_SB { get; set; }
		public string Login { get; set; }
		public string Name_Manager { get; set; }
		public string Surname_Manager { get; set; }
		public string Name_Company { get; set; }
		public string Name_Client { get; set; }
		public string Post_Client { get; set; }
	}
}

AdminWeb/Models/DeviceModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class DeviceModel
	{
		public int ID { get; set; }
	    public string Type { get; set; }
        public string Block { get; set; }
        public string Display { get; set; }
        public string Header { get; set; }
        public string Name { get; set; }
		public string Price { get; set; }
        public string Description { get; set; }
        
		//public List <DescriptionModel> Description { get; set; }

	}
}

AdminWeb/Models/Headers.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Windows.Media;
using Faster_Kp_Client.Annotations;

namespace AdminWeb.Models
{
	public class Headers : INotifyPropertyChanged
	{
		private string _head;
		public string Head
		{
			get => _head;
			set
			{
				_head = value;
				OnPropertyChanged();
			}
		}
		private ObservableCollection<Item> _collection;
		public ObservableCollection<Item> Collection
		{
			get => _collection ?? (_collection = new ObservableCollection<Item>());
			set
			{
				_collection = value;
				OnPropertyChanged();
			}
		}


		public event PropertyChangedEventHandler PropertyChanged;

		[NotifyPropertyChangedInvocator]
		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}

	public class CollectHeads
	{
		private ObservableCollection<Headers> _headerses;

		public ObservableCollection<Headers> Headerses
		{
			get => _headerses ?? (_headerses = new ObservableCollection<Headers>());
			set => _headerses = value;
		}
	}
	public class Item : INotifyPropertyChanged
	{
		private string _property;
		public string Property
		{
			get => _property;
			set
			{
				_property = value;
				OnPropertyChanged();
			}
		}
		private string _price;
		public string Price
		{
			get => _price;
			set
			{
				_price = value;
				OnPropertyChanged();
			}
		}
	    private string _desc;
	    public string Desc
	    {
	        get => _desc;
	        set
	        {
	            _desc = value;
	            OnPropertyChanged();
	        }
	    }

        public event PropertyChangedEventHandler PropertyChanged;

		[NotifyPropertyChangedInvocator]
		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	public class ImageModels : INotifyPropertyChanged
	{
		private string _path;
		public string Path
		{
			get => _path;
			set
			{
				_path = value;
				OnPropertyChanged();
			}
		}
		private string _name;
		public string Name
		{
			get => _name;
			set
			{
				_name = value;
				OnPropertyChanged();
			}
		}



		public event PropertyChangedEventHandler PropertyChanged;

		[NotifyPropertyChangedInvocator]
		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

AdminWeb/Models/ResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class ResultModel
	{
		private string _text { get; set; }
		public string Text
		{
			get => _text;
			set => _text = value;
		}
	}
}

AdminWeb/Models/TypesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
    public class TypesModel
    {
        public bool IS { get; set; }
        public bool IP { get; set; }
        public bool SK { get; set; }
        public bool ST { get; set; }
    }
}

AdminWeb/Models/UploadModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class UploadModel
	{
		public byte[] pathd { get; set; }
		public byte[] pathe { get; set; }
		public string login { get; set; }
		public string name { get; set; }
		public int ID { get; set; }
	}
}

AdminWeb/Models/UserContext.cs
using AdminWeb.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using Faster_Kp_Client.KPPages;

namespace AdminWeb.Models
{
	public class UserContext:DbContext
	{
		public UserContext() :
			base("FastersKpDB")
		{ }
		public DbSet<UserModel> UserModels { get; set; }
        public DbSet<BaseModel> BaseModels { get; set; }
        public DbSet<DeviceModel> DeviceModels { get; set; }
    }
}

AdminWeb/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public class LoginModel
	{
		[Required]
		public string Login { get; set; }

		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }
	}
	public class RegisterModel
	{
		[Required]
		public string Name { get; set; }

		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }

		[Required]
		public int ID { get; set; }

		[Required]
		public string Login { get; set; }

		[Required]
		public string Position { get; set; }

		[Required]
		public string Surname { get; set; }

		[Required]
		public string Telefon_number { get; set; }

		[Required]
		public string Image_name { get; set; }
		[Required]
		public bool Is_admin { get; set; }
		[Required]
		public bool Is_active { get; set; }
	}
	public class UserModel
	{
		public int ID { get; set; }
		public string Login { get; set; }
		public string Password { get; set; }
		public string Name { get; set; }
		public string Position { get; set; }
		public string Surname { get; set; }
		public string Telefon_number { get; set; }
		public string Image_name { get; set; }
		public bool Is_admin { get; set; }
		public bool Is_active { get; set; }
	}	
}

AdminWeb/Models/UsersList.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;

namespace AdminWeb.Models
{
	public static class UsersList
	{
		private static ObservableCollection<UserModel> _users;

		public static ObservableCollection<UserModel> Users
		{
			get => _users ?? new ObservableCollection<UserModel>();
			set => _users = value;
		}
	}
}

AdminWeb/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Http;
using System.Web.Mvc;
using AdminWeb.Models;
using Microsoft.Office.Interop.Excel;

namespace AdminWeb.Controllers
{
    public class FilesController : Controller
    {
        // GET: Files
        public ActionResult Tables()
		{
			//if (User.Identity.IsAuthenticated)
			//{
				return View();
			//}
			//return RedirectToAction("Index", "Home");
		}

	    public CollectHeads Heads = new CollectHeads();

		[System.Web.Mvc.HttpPost]
	    [ValidateAntiForgeryToken]
	    public ActionResult DownloadFile(string path, string click, object file)
	    {
		    try
		    {
			    HttpPostedFileBase[] posted = (HttpPostedFileBase[]) file;
			    Stream stream = posted[0].InputStream;
			   
			    switch (click)
			    {
				    case "Body19,5":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\19,5\Body.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Body21,5":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\21,5\Body.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Body32":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\32\Body.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Body43":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\43\Body.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Body48":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\48\Body.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Body49":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\49\Body.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Body55":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\55\Body.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Body65":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\65\Body.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Body70":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\70\Body.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Typesensor19,5":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\19,5\Typesensor.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Typesensor21,5":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\21,5\Typesensor.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Typesensor32":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\32\Typesensor.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Typesensor43":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\43\Typesensor.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Typesensor48":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\48\Typesensor.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Typesensor49":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\49\Typesensor.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Typesensor55":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\55\Typesensor.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Typesensor65":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\65\Typesensor.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Typesensor70":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\70\Typesensor.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Computer":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\Computer.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);
						    fileStream.Write(data, 0, data.Length);
					    }

					    ;
					    break;
				    case "Display":
					    using (FileStream fileStream =
						    System.IO.File.Create(
							    System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath +
							    $@"base\{path}\Display.xlsx",
							    (int) stream.Length))
					    {
						    byte[] data = new byte[stream.Length];
						    stream.Read(data, 0, (int) data.Length);

AdminWeb/Views/Files/Additem.cshtml
@using AdminWeb.Models
@using Microsoft.Ajax.Utilities
@model System.Collections.ObjectModel.ObservableCollection<AdminWeb.Models.DeviceModel>

@using (Ajax.BeginForm("Saveitem", "Files", new AjaxOptions {UpdateTargetId = "message"}))
{
    <table border="1px" bordercolor="#777777">
        <tr>
            <th>Группа</th>
            <th>Подгруппа</th>
            <th>Тип оборудования(куда добавить)</th>
            <th>Тип</th>
            <th>Название</th>
            <th>Характеристика</th>
            <th>Цена</th>
        </tr>

        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                @if (i == 0)
                {
                    <td rowspan="@Model.Count">
                        <select class="changingblockall" name="Block1" >
                            @if (Model[i].Block == "Display") {<option value="Display" selected>Display</option> } else { <option value="Display">Display</option>}
                            @if (Model[i].Block == "Body") {<option value="Body" selected>Body</option> } else { <option value="Body">Body</option>}
                            @if (Model[i].Block == "Typesensor") {<option value="Typesensor" selected>Typesensor</option> } else { <option value="Typesensor">Typesensor</option>}
                            @if (Model[i].Block == "Computer") {<option value="Computer" selected>Computer</option> } else { <option value="Computer">Computer</option>}
                            @if (Model[i].Block == "ExtraDevice") {<option value="ExtraDevice" selected>ExtraDevice</option> } else { <option value="ExtraDevice">ExtraDevice</option>}
                        </select>
                    </td>
                }
                @if (i == 0 && Model[i].Header != "")
                {
                    <td rowspan="@Model.Count"><input type="text" class="changingheadersall" name="Header1" value="@Model[i].Header"/></td>
                }
                @if (Model[i].Header == "")
                {
                    <td><input type="text" class="changingheaders" name="Header1" value="@Model[i].Header"/></td>
                }
                @if (i == 0)
                {
                    <td rowspan="@Model.Count">
                        
                        <div id="checkkek">
                            @if (Model[i].Type.Contains("1"))
                            {
                                <input class="checkboxtype" type="checkbox" name="IS" checked value="1" />
                                <label>Столы</label>       
                            }                              
                            else                           
                            {                              
                                <input class="checkboxtype" type="checkbox" name="IS" value="1" />
                                <label>Столы</label>
                            }
                            @if (Model[i].Type.Contains("2"))
                            {
                                <input class="checkboxtype" type="checkbox" name="IP" checked value="2" />
                                <label>Панели</label>
                            }
                            else
                            {
                                <input class="checkboxtype" type="checkbox" name="IP" value="2" />
                                <label>Панели</label>
                            }
                            @if (Model[i].Type.Contains("3"))
                            {
                                <input class="checkboxtype" type="checkbox" name="SK" checked value="3" />
                                <label>Киоски</label>
                            }
                            else
                            {
                                <input class="checkboxtype" type="checkbox" name="SK" value="3" />
                                <label>Киоски</label>
                            }
                            @if (Model[i].Type.Contains("4"))
                            {
                                <input class="checkboxtype" type="checkbox" name="ST" checked value="4" />
                                <label>Терминалы</label>
                            }
                            else
                            {
                                <input class="checkboxtype" type="checkbox" name="ST" value="4" />
                                <label>Терминалы</label>
                            }
                            <input type="hidden" name="Type1" value="@Model[i].Type" />
                        </div>
                    </td>
                }
                @if (i == 0 && Model[i].Display != "")
                {
                    <td rowspan="@Model.Count"><input type="text" class="changingdisplayall" name="Display1" value="@Model[i].Display"/></td>
                }
                @if (Model[i].Display == "")
                {
                    <td><input type="text" class="changingdisplay" name="Display1" value="@Model[i].Display"/></td>
                }
                    <td id="sendmodel">
                        <input type="text" class="blocks" name="dv[@i].Block" hidden value="@Model[i].Block" />
                        <input type="text" class="headers" name="dv[@i].Header" hidden value="@Model[i].Header" />
                        <input type="text" class="types" name="dv[@i].Type" hidden value="@Model[i].Type" />
                        <input type="text" class="displays" name="dv[@i].Display" hidden value="@Model[i].Display" />
                        <input type="text" class="names" name="dv[@i].Name" />
                    </td>
                <td><textarea class="selectdesc" id="descsel" name="dv[@i].Description"></textarea></td>
                <td><input type="text" class="prices" name="dv[@i].Price"/>
                    <input type="hidden" name="dv[@i].ID" value="0"/></td>
            </tr>
        }

    </table>
    <input class="go" type="submit" hidden />
    <script>
   
    </script>
}

AdminWeb/Views/Files/ChangeType.cshtml
@model AdminWeb.Models.DeviceModel
<div id="completed">
    @if (Model.Type.Contains("1"))
    {
        <input class="checkboxtype"  type="checkbox" name="IS" checked value="1" />
        <label>Столы</label>
    }
    else
    {
        <input class="checkboxtype"  type="checkbox" name="IS" value="1" />
        <label>Столы</label>
    }
    @if (Model.Type.Contains("2"))
    {
        <input class="checkboxtype"  type="checkbox" name="IP" checked value="2" />
        <label>Панели</label>
    }
    else
    {
        <input class="checkboxtype"  type="checkbox" name="IP" value="2" />
        <label>Панели</label>
    }
    @if (Model.Type.Contains("3"))
    {
        <input class="checkboxtype"  type="checkbox" name="SK" checked value="3" />
        <label>Киоски</label>
    }
    else
    {
        <input class="checkboxtype"  type="checkbox" name="SK" value="3" />
        <label>Киоски</label>
    }
    @if (Model.Type.Contains("4"))
    {
        <input class="checkboxtype"  type="checkbox" name="ST" checked value="4" />
        <label>Терминалы</label>
    }
    else
    {
        <input class="checkboxtype"  type="checkbox" name="ST" value="4" />
        <label>Терминалы</label>
    }
    <input type="hidden" id="changing" name="DeviceModel.Type" value="@Model.Type" />
</div>
@using (Ajax.BeginForm("ChangeType", "Files", new AjaxOptions { UpdateTargetId = "checktypes" }))
{
    <input type="hidden" name="Block"  value="@Model.Block"/>
    <input type="hidden" name="Header" value="@Model.Header" />
    <input type="hidden" name="Display" value="@Model.Display" />
    <input type="hidden" name="Name"   />
    <input type="submit" hidden />
}

AdminWeb/Views/Files/LoginFile.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LoginFile</title>
</head>
<body>
    @using (Html.BeginForm("GetBaseClientManager", "Files"))
    {
        <label>Введите логин и пароль, чтобы получить клиентскую базу</label>
        <br />
        <input type="text" name="login" /><br />
        <input type="password" name="password" />
        <br />
        <input type="submit" name="sub" />
    }
</body>
</html>

AdminWeb/Views/Files/Models.cshtml
@model string[]
@{
    ViewBag.Title = "Модели оборудования";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Оборудование</title>
    <style>
        .folderbutton {
            border: solid 1px #b3b3b3;
            border-radius: 5px;
            transition-property: border;
            transition-delay: 100ms;
            outline: none;
        }
        .folderbutton:hover {
            border: solid 1px #3aaaf5f3;
        }
    </style>
</head>
<body>
    <label for="viewlist">Обзор</label>
<div id="viewlist">
    @foreach (string name in Model)
    {
        DirectoryInfo di = new DirectoryInfo(name);
        using (Ajax.BeginForm("GetModels", "Files", new AjaxOptions{UpdateTargetId = "viewlist"}))
        {
            <div>
                <input name="path" type="hidden" value="@name"/>
                <button class="folderbutton" type="submit">
                    <img style="margin: 5px" src="~/Icons/folder.png"/>
                    <br/>
                    <text style="text-align: center">@di.Name</text>
                </button>
            </div>
        }
        
    }
</div>
</body>
</html>

AdminWeb/Views/Files/PutDevice.cshtml
<h1>ВЫБЕРИТЕ ТИП</h1>

AdminWeb/Views/Files/SaveChanges.cshtml
@model string
<img src="@Model" />

AdminWeb/Views/Files/Saveitem.cshtml
<h1>СОХРАНЕНО</h1>
<p>для отражения результатов нажмите "ОБНОВИТЬ"</p>

AdminWeb/Views/Files/SelectDescription.cshtml
@using AdminWeb.Models
@model System.Collections.ObjectModel.ObservableCollection<DeviceModel>
@foreach (DeviceModel y in Model)
{
<textarea class="selectdesc" name="DeviceModel.Description">@y.Description</textarea>
}

AdminWeb/Views/Files/SelectNames1.cshtml
@using AdminWeb.Models
@model System.Collections.ObjectModel.ObservableCollection<DeviceModel>

<select class="selectname" name="DeviceModel.Name">
    <option value="" selected disabled hidden>Название</option>
    @foreach (DeviceModel device in Model.OrderBy(t=>t.Name))
    {
        <option value="@device.Name">@device.Name</option>
    }
</select>

AdminWeb/Views/Files/SelectNames2.cshtml
@using AdminWeb.Models
@model System.Collections.ObjectModel.ObservableCollection<DeviceModel>

<select class="selecttype" name="DeviceModel.Display">
    <option value="" selected disabled hidden>Тип</option>
    @foreach (DeviceModel device in Model)
    {
        <option value="@device.Display">@device.Display</option>
    }
</select>

AdminWeb/Views/Files/SelectPrice.cshtml
@using AdminWeb.Models
@model System.Collections.ObjectModel.ObservableCollection<DeviceModel>

@foreach (DeviceModel y in Model)
{
    using (Ajax.BeginForm("SaveChanges", "Files", new AjaxOptions { UpdateTargetId = "status" + @y.Block + @y.Header.Replace(" ", "_") }))
    {

        <input type="hidden" name="dv.Block" value="@y.Block" />
        <input type="hidden" name="dv.Header" value="@y.Header" />
        <input type="hidden" name="dv.Type" value="@y.Type" />
        <input type="hidden" name="dv.Display" value="@y.Display" />
        <input class="selectprice" name="dv.Price" type="text" value="@y.Price"/>
        <input type="hidden" name="dv.Name" value="@y.Name" />
        <input type="hidden" name="dv.Description" value="@y.Description" />
        <input type="hidden" name="dv.ID" value="@y.ID" />
        <input type="submit" hidden />
        <input type="hidden" class="method" name="met" value="" />
    }

}

AdminWeb/Views/Files/SetDollar.cshtml
@model string

<text>@Model</text>

AdminWeb/Views/Files/SetTable.cshtml
@model string
<text>@Model</text>